version: '3.8'
services:
  dnd_bot:
    build: .
    container_name: dnd_bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./dnd_bot.db:/app/dnd_bot.db
    ports:
      - "8080:8080"
    command: ["python", "bot.py"]
